* Matt Laine Literate Emacs Config

** Startup Screen + Geometry

This makes the startup screen and general geometry not look like total crap, and <ESC> to quit prompts in addition to C-g

#+begin_src emacs-lisp

  (setq inhibit-startup-message t)

  (scroll-bar-mode -1)                     ; Disable visible scroll bar
  (tool-bar-mode -1)                       ; Disable the toolbar
  (tooltip-mode -1)                        ; Disable tooltips
  (global-set-key
   (kbd "<escape>") 'keyboard-escape-quit) ; Make ESC quit prompts
  
#+end_src

** Font + theme.

I prefer Monoid font over the other stuff, but you have to have installed it first. You can find it at https://github.com/larsenwork/monoid

Wombat theme is available as a default theme with Emacs.

#+begin_src emacs-lisp
  
  (set-face-attribute
   'default nil
   :font "Monoid"
   :height 156)

  (load-theme 'wombat)

#+end_src

** Package initialization

#+begin_src emacs-lisp
  
  (require 'package)
  (setq package-archives
	'(("melpa" . "https://melpa.org/packages/")
	  ("org"   . "https://orgmode.org/elpa/")
	  ("elpa"  . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)

#+end_src

** Packages

*** Evil Mode

For me, this is necessary. I can neither stand nor remember vanilla Emacs bindings. This is the first package I install, because without it I'm dingdonging around like a doofus.

#+begin_src emacs-lisp

  (use-package evil
    :config
    (evil-mode 1))
  
#+end_src

*** TODO Magit

#+begin_src emacs-lisp

  (use-package magit)
  
#+end_src

*** Ivy

#+begin_src emacs-lisp

  (use-package ivy
    :bind (; TODO Install Swiper ("C-s" . swiper)
	   :map ivy-minibuffer-map
	   ("TAB" . ivy-alt-done)
	   ("C-l" . ivy-alt-done)
	   ("C-j" . ivy-alt-done)
	   ("C-k" . ivy-previous-line)
	   :map ivy-switch-buffer-map
	   ("C-k" . ivy-previous-line)
	   ("C-l" . ivy-done)
	   ("C-d" . ivy-switch-buffer-kill)
	   :map ivy-reverse-i-search-map
	   ("C-k" . ivy-previous-line)
	   ("C-d" . ivy-reverse-i-search-kill))
    :config
    (ivy-mode 1))

#+end_src

*** Command Log Mode

#+begin_src emacs-lisp

  (use-package command-log-mode)

#+end_src

*** Prettification

**** Rainbow delimiters

#+begin_src emacs-lisp

  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))

#+end_src

** Line Numbering

Display line numbers everywhere except term-mode and eshell-mode

#+begin_src emacs-lisp

  (global-display-line-numbers-mode)
  (dolist (mode '(term-mode-hook
		  eshell-mode-hook
		  shell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))
  
#+end_src
